#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse
import pandas as pd
from toolbox.regex import *

if __name__ == '__main__':
    description = 'stkrgcp_description'
    parser = argparse.ArgumentParser(description=description)
    parser.add_argument('--text',
                        nargs='+',
                        help='Example here')
    args = parser.parse_args()
    text = args.text
    url = get_url(text)
    print("###### YOUR URL ######")
    print(url)
